# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c5c8b45dd93bf889cab81278cf07da08319c2472dc97e03609f6004e89bf2cbaa3c5a4e28f72d51762aea4c5100adc0f9da2665d92637e41113978828a56f3

test:
  secret_key_base: f6a5f48451fbdb4e883facf71a0b310688cc51b6bccefdbe544d3d582d8e0e63fa9b7c6a79f88567857dbd59bf3cd22935c2dc26a88135f31fdb7cf798397bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
